//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputInfo
    {
        public string Id { get; set; }
        public string ProductID { get; set; }
        public string OutputID { get; set; }
        public string CustomerID { get; set; }
        public string InputInfoID { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual InputInfo InputInfo { get; set; }
        public virtual Output Output { get; set; }
        public virtual Product Product { get; set; }
    }
}
